### ISSUE TITLE
Source of yerba.json

### ISSUE THREAD

**Issue by KONRADS098** [wzium/Yerbus#2]
Would you mind sharing the data source used to construct `yerba.json`?

**Comment by wzium** [comment]
I gathered it manually using most popular yerba mate store websites from Poland (ymt24.pl and dobreziele.pl). I update it from time to time when there is a drop of new products. I also received support from the ymt24.pl owner - Mateusz Skotnicki.

If you have any questions, feel free to contact me via Discord - jjay31
